#!/opt/homebrew/bin/python3
# Generated by google Gemini https://share.gemini.google/772hPbxjX7EA

import sys


def split_file_by_stream(filename: str, num_streams: int) -> None:
    # Extract base filename without extension
    base_name = filename.rsplit(".", 1)[0] if "." in filename else filename

    # Open output files for each stream
    out_files = [
        open(f"{base_name}_stream-{i}.txt", "w", encoding="utf-8")
        for i in range(num_streams)
    ]

    try:
        with open(filename, "r", encoding="utf-8") as infile:
            for line_number, line in enumerate(infile):
                stream_index = line_number % num_streams
                out_files[stream_index].write(line)
    finally:
        # Ensure all open files are properly closed
        for f in out_files:
            f.close()


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python script.py <input_file.txt> <num_streams>")
        sys.exit(1)

    input_filename = sys.argv[1]

    try:
        streams = int(sys.argv[2])
        if streams <= 0:
            raise ValueError
    except ValueError:
        print("Error: stream number must be a positive integer.")
        sys.exit(1)

    try:
        split_file_by_stream(input_filename, streams)
        print(f"Successfully split '{input_filename}' into {streams} stream files.")
    except FileNotFoundError:
        print(f"Error: File '{input_filename}' not found.")
        sys.exit(1)